language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - py.test --cov=. --cov-config .coveragerc .

after_success:
  - coverage xml
  - coveralls
